name: build-apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # اختياري: تثبيت بايثون (بعض خطوات buildozer تحتاجه)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # هذا الأكشن يوفّر بيئة Buildozer + Android SDK/NDK تلقائياً
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: polymarket-btc-helper-apk
          path: bin/*.apk
